name: pipeline-experimental
on: pull_request
jobs:
  ci-continious-intagracion:
    name: teste de ci
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ol√°, FATEC!"
        name: mansagem especial
      - uses: actions/checkout@v5
        name: fazendo clone e checkout no meu repositorio nesta maquina virtual
      - name: zipar os arquivos do meu repositorio
        run: zip -r arquivo.zip .
      - name: listarr os arquivos do meu repositorio
        run: ls -la
