name: pipeline-experimental
on: 
  push: 
    branches: [main, develop]
jobs:
  testes:
    name: job 1 Testes
    runs-on: ubuntu-latest
    steps:
      - name: passo 1 checkout
        uses: actions/checkout@v5
      - name: passo 2 setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: passo 3 install dependences
        run: npm ci
      - name: passo 4 run test
        run: npm run test
  build:
    name: job 2 Build
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
  deploy:
    name: job 3 Deploy
    runs-on: ubuntu-latest
    steps:
      - run: npm run deploy