name: Workflow Manual
on:
#  push:
#    branches:
#      - main
#  schedule:
#    - cron: '0 2 * * *'
  workflow_dispatch:
    input:
      rodar_teste:
        description: 'Rodar testes antes do deploy?'
        required: true
        default: 'sim'
        type: choice
        options:
          - sim
          - nao
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout c√≥digo
        uses: actions/checkout@v4